### ISSUE TITLE
[Bug] The app crashes because it doesn't load the images properly

### ISSUE THREAD

**Issue by sgamesdev** [Leo-Corporation/Gavilya#246]
### What is the bug?

Well , after the  splash screen , it crashes

### How to reproduce the bug?

i think it happens because it doesn't load the images properly

### Screenshots

![Capture32](https://user-images.githubusercontent.com/72159024/174311822-3f975b29-2972-4293-bc83-8c71bb55bfe5.PNG)

### Operating System

Windows 10

### What is the version of the operating system?

win 20h2

### What is the version of the software?

latest

**Comment by Leo-Peyronnet** [comment]
Thanks for reporting this issue. Will release a fix a soon as possible.

**Comment by Leo-Peyronnet** [comment]
The issue should now be fixed.
