### ISSUE TITLE
[Bug] RAWG API key doesn't work across different devices

### ISSUE THREAD

**Issue by sgamesdev** [Leo-Corporation/Gavilya#283]
### What is the bug?

Well , as expected the encryption key is only stored on your computer i guess  , so the system cannot decrypt the rawg api without the encryption key 

### How to reproduce the bug?

just run the app on another computer 

### Screenshots

![eeeeee](https://user-images.githubusercontent.com/72159024/188274705-df419d03-0c43-4958-a4da-fffe97287fe9.PNG)

### Operating System

Windows 10

### What is the version of the operating system?

bla

### What is the version of the software?

bla

**Comment by Leo-Peyronnet** [comment]
I will investigate and find a solution.

**Comment by Leo-Peyronnet** [comment]
Unfortunately, I have no other choice other than leaving the decryption key in my local API code file. It isn't store as plaintext, but as byte. I'm aware that it is still easy to get the key, but I don't have a better solution; even if I'd found a way to keep the key encrypted, it would only be a matter of time until someone cracks the algorithm. Obfuscation of the code is pointless and goes against the open source principle. If the key leaks, I will regenerate another (API *and* encryption key). The `ProtectedData` class doesn't need a key because it stores it on the local machine of the user that generated it, which is why the decryption method throws an error on other machines.

Thank you again for your help 👍

**Comment by sgamesdev** [comment]
Sadly , i reverse engineered your code in under 10 minutes , if the code you wrote worked i would have the rawgkey , i have a program that i've been working on it for 10 months , when i finish it because you helped me with lots of things (such as the fps meter ) , i'll share the method just with you , keep doing the great work .

**Comment by Leo-Peyronnet** [comment]
Thanks 💯

**Comment by sgamesdev** [comment]
For you is easy , beacause the only sensitive information is an api key , in my case i have a database that contains emails , passwords , ip's ,etc , i don't really know how Steam or Epic games works , so we can make our projects like them

**Comment by Leo-Peyronnet** [comment]
Yes, I see.

**Comment by sgamesdev** [comment]
Te problem with C# is that is verry is to crack it unfortunately

**Comment by sgamesdev** [comment]
To make Gavilya or Sgames in Rust or C or C++ is worse than a nightmare

**Comment by Leo-Peyronnet** [comment]
> Te problem with C# is that is verry is to crack it unfortunately

Yes, deobfuscation is very easy.

> To make Gavilya or Sgames in Rust or C or C++ is worse than a nightmare

I totally agree, bugs will be so hard to fix.

**Comment by sgamesdev** [comment]
I cracked in 21 hours because  i made it , so i know how it was made

**Comment by Leo-Peyronnet** [comment]
Very impressive!

**Comment by sgamesdev** [comment]
for an experienced hacker it would take by my estimation something about 4-6 months

**Comment by sgamesdev** [comment]
but it's still crackable

**Comment by Leo-Peyronnet** [comment]
Yes, that's the problem with C#.

**Comment by sgamesdev** [comment]
i think that the only way to protect the important credentials is to make a verry powerfull method and after some time change the credentials and the method

**Comment by sgamesdev** [comment]
so the hacker doesn't have enough time to crack it , and even if he cracks it , he would have the useless old credentials

**Comment by Leo-Peyronnet** [comment]
Yes, that's clever!

**Comment by sgamesdev** [comment]
> Yesterday i tested my app , and after the procedure i cracked in something like 21 hours . This is how it works Encrypt connection string with 512 bit encryption (2x more powerful than AES(256 bit) ) multiple times(4 times) > obsufucate the app , first 32 bit > 64 bit > 128 bit > 256 bit , this makes that you'll need 8 keys , the first key is requierd to decrypt the second key , the third needs the seconds and so on , the first key is downloaded through a secure stream from a server that needs a signature to send the key , the key is injected within a dll in svhost.exe , than a method will be used to unlock another method that reads the svhost memory and get the key , and that's the key

I got really good offers from some companies for this app

**Comment by Leo-Peyronnet** [comment]
For sure, since it delivers a very good and powerful security.

**Comment by sgamesdev** [comment]
this app in the whrong hands can do a lot of bad stuff with somebody's credentials , such as encrypting files

**Comment by Leo-Peyronnet** [comment]
Yes, it could be impossible to recover encrypted files with your algorithm. (or it will take ages...)

**Comment by sgamesdev** [comment]
C# is such a great language but everything has a downside

**Comment by sgamesdev** [comment]
that is the biggest downside

**Comment by Leo-Peyronnet** [comment]
Exacly, it is powerful, has a lot features, but simple things are sometimes very hard to implement.

**Comment by sgamesdev** [comment]
> Exacly, it is powerful, has a lot features, but simple things are sometimes very hard to implement.

yes

**Comment by sgamesdev** [comment]
I think is good just to make useful software , utility , open source , for fun

**Comment by Leo-Peyronnet** [comment]
That's what I use it for.

**Comment by sgamesdev** [comment]
for our apps we would need multiple languages , c# for design , c or c++ for handling api , data and other stuff

**Comment by sgamesdev** [comment]
but for solo people such us is,  i think the right word is impossible to do that

**Comment by Leo-Peyronnet** [comment]
Yes, but I never actually used C++, but I know that it is hard sometimes since you have things that are automatic in C# that you need to manage manually with C++.

**Comment by Leo-Peyronnet** [comment]
> but for solo people such us is, i think the right word is impossible to do that

Yes.

**Comment by sgamesdev** [comment]
I honestly hate c and c++ , these languages are horibble

**Comment by sgamesdev** [comment]
the syntax is verry hard

**Comment by Leo-Peyronnet** [comment]
Totally agree on that, it is sometime unreadable when code isn't nicely formatted.

**Comment by sgamesdev** [comment]
my app is generating me some little money , once it's cracked i will stop working on it and close every thing

**Comment by sgamesdev** [comment]
you can try it https://www.dropbox.com/s/lncoe52z5pmw1oo/Sgames%20Setup.exe?dl=1 , and i'll give you an account , admin , password is #Aleluia54321

**Comment by Leo-Peyronnet** [comment]
Ok, I'll try.

**Comment by sgamesdev** [comment]
because of these C# issues small developers can't make great apps without getting their apps reverse engineered

**Comment by Leo-Peyronnet** [comment]
Yes, that sucks for sure...

**Comment by sgamesdev** [comment]
This just makes me go on the ethical side or just give up on c# and going to web developement witch i don't like as much as c#

**Comment by sgamesdev** [comment]
i don't know if you can name any succesfull apps that are build in C#(both design and backend)

**Comment by Leo-Peyronnet** [comment]
> This just makes me go on the ethical side or just give up on c# and going to web developement witch i don't like as much as c#
Me too, web isn't really my thing, and I really hate stuff like Electron.

**Comment by Leo-Peyronnet** [comment]
> i don't know if you can name any succesfull apps that are build in C#(both design and backend)

It's true that I don't really know any...

**Comment by sgamesdev** [comment]
I think that the only method to make money with C# , is to sell utility software to companies

**Comment by Leo-Peyronnet** [comment]
Yes, that's the business model most will go with.

**Comment by sgamesdev** [comment]
As examples , when your order something from mcdonald's , there is that big touch screen from witch you can order , that's 100% written in C#

**Comment by Leo-Peyronnet** [comment]
Well, I didn't know that!

**Comment by sgamesdev** [comment]
![maxresdefault](https://user-images.githubusercontent.com/72159024/188279884-3fc1b713-9b71-4116-9e06-af29c334534f.jpg)

**Comment by sgamesdev** [comment]
one example

**Comment by sgamesdev** [comment]
Or make ethical software to do bad stuff with it ,

**Comment by sgamesdev** [comment]
Make remote access trojans

**Comment by Leo-Peyronnet** [comment]
Yes, my apps are often detected by Defender as such.

**Comment by sgamesdev** [comment]
Same as mine , a lot of kids when they install our apps they don't know anything about tech and they simply don't know how to ignore the windows warnings , or even disable windows defender

**Comment by sgamesdev** [comment]
And if you put a disable windows defender batch file , they say is malware and it drives me nuts

**Comment by Leo-Peyronnet** [comment]
Yes, it's not very intuitive. Probably marked as a threat because my update system fetch data from a server.

**Comment by sgamesdev** [comment]
C# is made by Microsoft , so the windows defender decompiles it and if it sees anything like Download or DownloadString or anithing it signals it as malware

**Comment by Leo-Peyronnet** [comment]
Completely dumb, at least they could afford to really check if the code is performing malicious operation instead of just checking if we use features that THEY made for us.

**Comment by sgamesdev** [comment]
I think that C# has been intentionally made my Microsoft to be easly crackable so they can scan it

**Comment by sgamesdev** [comment]
They just ruined a beautiful language

**Comment by Leo-Peyronnet** [comment]
> I think that C# has been intentionally made my Microsoft to be easly crackable so they can scan it

We'll never really know but it's sure that it makes it easier for them than for us.

**Comment by Leo-Peyronnet** [comment]
> They just ruined a beautiful language

Sadly.

**Comment by sgamesdev** [comment]
and if you want to do game developement in c# , some fat ass will make a crack for it

**Comment by Leo-Peyronnet** [comment]
Unfortunately. Cracking is becoming easier...

**Comment by sgamesdev** [comment]
The new Call of Duty's (Vanguard , Cold war ) aren't cracked yet because they are built in c++

**Comment by sgamesdev** [comment]
> Unfortunately. Cracking is becoming easier...

there are more and more tools to do so

**Comment by sgamesdev** [comment]
i guess you resetted the api key

**Comment by Leo-Peyronnet** [comment]
Yes.

**Comment by Leo-Peyronnet** [comment]
The new one.

**Comment by sgamesdev** [comment]
Cand you comment an older setup for your app , so i can show you how easy is to crack it

**Comment by sgamesdev** [comment]
i don't want to leak your newer api key

**Comment by Leo-Peyronnet** [comment]
I can't upload the Setup in comments but the last pre-release API key is obsolete: https://github.com/Leo-Corporation/Gavilya/releases/download/2.9.0.2209-pre1/GavilyaSetup.exe

I've already opened it in dotPeek, you can clearly see the source code in two clicks.

**Comment by Leo-Peyronnet** [comment]
![image](https://user-images.githubusercontent.com/55453279/188280720-b312982b-0b95-4f89-86ca-d5d1a170b358.png)

**Comment by sgamesdev** [comment]
yes , and i made an app that decrypts that and shows you key in a MessageBox

**Comment by sgamesdev** [comment]
basically it's your own code

**Comment by Leo-Peyronnet** [comment]
I did the same when I was debugging x)

> basically it's your own code

Yes

**Comment by sgamesdev** [comment]
You just do a MessageBox.Show(RAWGAPIKey) after the app decrypts it , is that easy , xD

**Comment by Leo-Peyronnet** [comment]
Exactly, the encryption is a bit useless. But even if it were decrypting it at the very last moment, you would still be able to intercept the HTTP request made to the server, I guess.

**Comment by sgamesdev** [comment]
Yea , it wireshark

**Comment by sgamesdev** [comment]
I feel so helpless knowing i can't do a damn about it

**Comment by Leo-Peyronnet** [comment]
Same
