### ISSUE TITLE
[Misc] The FPS counter doesn't work on a lot games

### ISSUE THREAD

**Issue by sgamesdev** [Leo-Corporation/Gavilya#290]
### Description of your issue

The fps counter doesn't work on a lot games including grand theft auto 5 and many others , you should try find a repository that injects dlls into games

**Comment by Leo-Peyronnet** [comment]
Yes, I was aware of this problem. Currently, only DirectX games are supported by the FPS counter. In the future, I plan to add new features, and extend its support to more games.
