### ISSUE TITLE
[Enhancement] Improve RAWG.io integration

### ISSUE THREAD

**Issue by Copeman-1** [Leo-Corporation/Gavilya#363]
### Enhancement

when you add a game and you  click the button RAWG.io on info and select the game info you want the data from that should carry over to the next section Integrations for RAWRG.io so you dont have to search for the game twice and to make it faster when adding a game, and for adding steam games would be cool if it could search for games & auto add games In SteamLibrary Folders
most people have alot of games on steam that they play

**Comment by Leo-Peyronnet** [comment]
Thank you for your suggestion. I will try to improve the RAWG integration in the next version of Gavilya. Will also consider improving the Steam integration too.
