### ISSUE TITLE
[Bug] Exception when running Gavilya library in list mode

### ISSUE THREAD

**Issue by Bamboooz** [Leo-Corporation/Gavilya#436]
### What is the bug?

I was trying to contribute to Gavilya, (note: this error does not exist in the .exe app download that you posted on github but only when running from the source). I was messing with the library view systems, when opening the library, and pressing on any game that you have (both for steam and local .exe files) the application crashes. The bug appears even with freshly downloaded code, so its not something wrong with stuff I changed.

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. Arg_ParamName_Name
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Gavilya.ViewModels.GamePageViewModel.<LoadRawg>d__130.MoveNext() in C:\Users\Bambu\Pulpit\Gavilya-4.2.0.2311\Gavilya\ViewModels\GamePageViewModel.cs:line 265

GamePageViewModel.cs, Line 265
![image](https://github.com/Leo-Corporation/Gavilya/assets/83116089/434d1767-f00f-486c-b42e-f4a4f5aac009)

### How to reproduce the bug?

1) Clone Gavilya repository,
2) Open Gavilya.sln in visual studio
3) Launch the app
5) Open games library
6) Click on any game

### Screenshots

![image](https://github.com/Leo-Corporation/Gavilya/assets/83116089/1a886e2b-60e8-4469-939b-cf577d99bc28)

### Operating System

Windows 10

### What is the version of the operating system?

Windows 10 22H2 19045.3693

### What is the version of the software?

v.4.2.0.2311

**Comment by Leo-Peyronnet** [comment]
Thanks for reporting this, I will investigate.

**Comment by Bamboooz** [comment]
![image](https://github.com/Leo-Corporation/Gavilya/assets/83116089/f23f6cc9-55f9-4813-9976-af594e478ad0)

After updating the code, new error arrises, I think the Platforms cannot be null as other pieces depend on it

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Gavilya
  StackTrace:
   at Gavilya.ViewModels.GamePageViewModel.<LoadRawg>d__130.MoveNext() in C:\Users\Bambu\Pulpit\Gavilya-4.2.0.2311\Gavilya\ViewModels\GamePageViewModel.cs:line 271

**Comment by Bamboooz** [comment]
also appears only when pressing on a game in the library tab

**Comment by Bamboooz** [comment]
i also forgot to mention this bug only exists when running from the code, not the application itself

**Comment by Leo-Peyronnet** [comment]
> After updating the code, new error arrises.

The code bellow should fix this issue.

``` cs
// Ratings section
if (rawgGame?.Ratings != null)
{
	rawgGame?.Ratings.ForEach((r) => { _totalRatings += r.Count; });
	rawgGame?.Ratings.ForEach(AssignRating);
	Rating = $"{rawgGame?.Rating:0.00}";
}
```

**Comment by Bamboooz** [comment]
yep, now works, but this is still really weird, are you sure that the newest app executable code is synced to github? these differences should not be appearing

**Comment by Leo-Peyronnet** [comment]
Yes, the code is correctly synced, this issue may be related to the way you added games or configured Gavilya on your machine. On mine, without the fixes I provided, the app didn't crash or had any issue when trying to reproduce the bug. 

The bug was related to some collections being `null` - this should no longer happen since I added multiple null checks.

**Comment by Bamboooz** [comment]
If you cannot replicate the issue, I will try to investigate it myself. I looked a bit more into it and yesterday some games, (but not all) rawg data started to work. It might even be the database issue itself, but I will try to fix it in the pull request with other changes I am planning to contribute. I will mark this issue as solved.
