### ISSUE TITLE
[Enhancement] Handle .lnk, instead game data folder search

### ISSUE THREAD

**Issue by Klemci** [Leo-Corporation/Gavilya#451]
### Enhancement

Because newcomers that want to use the launcher (instead the start menu links), having shortcuts .lnk files of all the games in one folder (and subfolders) could import all their games with ICON and ARGuments too already correct.

### Other informations

I have all links in a folder (Jeux PC) in start menu, i wanted a tool that lists this .lnk links files, display as big icons, keep dir tree, and close on launch (that was all the dea), i heard about this one lightweight launcher in my topic there.

**Comment by Leo-Peyronnet** [comment]
Hi,
Thanks for your suggestion! I will try to implement it in a future update.

**Comment by Klemci** [comment]
Look, a dev answered and i will use this (for now)... i know him by Shortcuts Search and replace (dir, ico...).

http://jacquelin.potier.free.fr/QuickWayToFolders/
